#  _____          _        __   __ _    __  __ _     
# |_   _| __ __ _(_)_ __   \ \ / // \  |  \/  | |    
#   | || '__/ _` | | '_ \   \ V // _ \ | |\/| | |    
#   | || | | (_| | | | | |   | |/ ___ \| |  | | |___ 
#   |_||_|  \__,_|_|_| |_|   |_/_/   \_\_|  |_|_____|
                                                   
batch_size: 32
learning_rate: 0.001
epochs: 10
transform_list:
  - name: RandomHorizontalFlip
  - name: RandomCrop
    size: 28
    padding: 4
  - name: ToTensor
  - name: Normalize
    mean: [0.1307]
    std: [0.3081]
optimizer_type: Adam
optimizer_hyperparams:
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0
annealing_type: StepLR
annealing_hyperparams:
  step_size: 5
  gamma: 0.1
