#  _____          _        __   __ _    __  __ _     
# |_   _| __ __ _(_)_ __   \ \ / // \  |  \/  | |    
#   | || '__/ _` | | '_ \   \ V // _ \ | |\/| | |    
#   | || | | (_| | | | | |   | |/ ___ \| |  | | |___ 
#   |_||_|  \__,_|_|_| |_|   |_/_/   \_\_|  |_|_____|
                                                   
batch_size: 16
learning_rate: 0.001
epochs: 1
transform_list:
  - name: ToTensor
  - name: Normalize
    mean: [0.1307]
    std: [0.3081]
optimizer_type: SGD
save_every: 1
test_every: 1